heat_template_version: 2016-10-14

description: Simple VM for lab3

parameters:
  KEY_NAME:
    type: string
    description: SSH keypair name
  IMAGE:
    type: string
    description: Image name
  FLAVOR:
    type: string
    description: Flavor name
  NETWORK_NAME:
    type: string
    description: Existing Neutron network name

resources:
  lab3_server:
    type: OS::Nova::Server
    properties:
      name: lab3-vm
      key_name: { get_param: KEY_NAME }
      image:    { get_param: IMAGE }
      flavor:   { get_param: FLAVOR }
      networks:
        - network: { get_param: NETWORK_NAME }

outputs:
  server_name:
    description: Name of created server
    value: { get_attr: [ lab3_server, name ] }
