heat_template_version: 2016-10-14

description: >
  Шаблон для создания одного сервера BigDwarf
  с flavor m1.small, образом ununtu-22.04,
  в сети students-net, c группой безопасности students-general
  и ключом RomanS1.

parameters:
  FLAVOR:
    type: string
    default: m1.small
  IMAGE:
    type: string
    default: ununtu-22.04
  NETWORK_NAME:
    type: string
    default: students-net
  SEC_GROUP:
    type: string
    default: students-general
  KEY_NAME:
    type: string
    default: RSelishchevMain
  SERVER_NAME:
    type: string
    default: Lab3

resources:
  bigdwarf_server:
    type: OS::Nova::Server
    properties:
      name:        { get_param: SERVER_NAME }
      flavor:      { get_param: FLAVOR }
      image:       { get_param: IMAGE }
      key_name:    { get_param: KEY_NAME }
      security_groups:
        - { get_param: SEC_GROUP }
      networks:
        - network: { get_param: NETWORK_NAME }

outputs:
  server_name:
    description: Имя созданного сервера
    value: { get_attr: [ bigdwarf_server, name ] }
